config/routes.rb
Rails.application.routes.draw do



  root "pages#index"
  get "/how", to: "pages#show", as: :how
  get "/dashboard", to: "users#show", as: "dashboard"

  resources :users, except: [:new, :show]
  resources :students, only: [:index, :show, :new, :create, :edit]
  resources :mentors, only: [:index, :show, :new, :create]
  resources :posses

  get "/deactivate-student", to: "students#deactivate", as: "deactivate_student"
  get "/activate-student", to: "students#activate", as: "activate_student"
  get "/deactivate-mentor", to: "mentors#deactivate", as: "deactivate_mentor"
  get "/activate-mentor", to: "mentors#activate", as: "activate_mentor"
  get "/lets-go", to: "users#new", as: "lets_go"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/auth/github", as: "login"
  get "/auth/:provider/callback", to: "sessions#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students
end

app/models/mentor.rb
class Mentor < ApplicationRecord
  belongs_to :user
  belongs_to :mentor_timezone

  validates :location, presence: true
  validates :mentor_timezone, presence: true
  validates :user, presence: true

  def name
    user.name
  end

  def timezone
    mentor_timezone.name
  end

  def picture
    user.picture
  end

  def email
    user.email
  end

  def slack_name
    user.slack_name
  end
end

app/models/mentor_timezone.rb
class MentorTimezone < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/posse.rb
class Posse < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :users
end

app/models/student.rb
class Student < ApplicationRecord
  validates :user_id, uniqueness: true
  belongs_to :user
  belongs_to :cohort

  def name
    user.name
  end

  def picture
    user.picture
  end

  def email
    user.email
  end

  def slack_name
    user.slack_name
  end

  def bio
    user.bio
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, presence: true, uniqueness: true
  validates :name, presence: true
  validates :picture, presence: true
  has_one :mentor
  has_one :student
  belongs_to :posse

  def self.find_or_create_from_auth(auth)
    info = auth['info']
    credentials = auth['credentials']

    user = User.find_or_create_by(uid: auth['uid'])
    user.name = info['name']
    user.picture = info['image']
    user.token = credentials['token']
    user.save
    user
  end

  def deactivate_student_profile
    student.update(active: false)
  end

  def activate_student_profile
    student.update(active: true)
  end

  def deactivate_mentor_profile
    mentor.update(active: false)
  end

  def activate_mentor_profile
    mentor.update(active: true)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to root_path unless current_user
  end

  def redirect_user
    redirect_to dashboard_path if current_user
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  def index
    @mentors = Mentor.all
  end

  def show
    @mentor = Mentor.find(params[:id])
  end

  def new
    @mentor = Mentor.new
    @timezones = MentorTimezone.all
  end

  def create
    @mentor = Mentor.new(mentor_params)
    @mentor.user_id = current_user.id
    if @mentor.save
      redirect_to mentors_path
    end
  end

  def activate
    if User.find(params[:id]).activate_mentor_profile
      flash[:success] = "Your profile was activated"
      redirect_to dashboard_path
    end
  end

  def deactivate
    if User.find(params[:id]).deactivate_mentor_profile
      flash[:danger] = "Your profile was deactivated"
      redirect_to dashboard_path
    end
  end

  private

  def mentor_params
    params.require(:mentor).permit(:location, :mentor_timezone_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/posses_controller.rb
class PossesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash.now[:danger] = "Something Happened"
      render root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.where(active: true)
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
    @cohorts = Cohort.all
  end

  def create
    student = Student.new(student_params)
    if student.save
      flash[:success] = "You now have a student profile!"
      redirect_to dashboard_path
    end
  end

  def edit
    @student = User.find(params[:id]).student
  end

  def deactivate
    if User.find(params[:id]).deactivate_student_profile
      flash[:danger] = "Your profile was deactivated."
      redirect_to dashboard_path
    end
  end

  def activate
    if User.find(params[:id]).activate_student_profile
      flash[:success] = "Your profile was activated."
      redirect_to dashboard_path
    end
  end

  private
  def student_params
    params.require(:student).permit(:cohort_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:new]
  before_action :redirect_user, only: [:new]

  def new
  end

  def show
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    @cohorts = Cohort.all
  end

  def update
    @user = User.find(params[:id])
    user = params[:user]
    if @user.update(email: user[:email], bio: user[:bio], slack_name: user[:slack_name])
      flash[:success] = "Your profile has been updated!"
      redirect_to dashboard_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :bio, :slack_name, :name)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mentorship</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container alert-container">
      <% if flash %>
        <% flash.each do |type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{type}") %>
        <% end %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/mentors/index.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>

<div class="container">
  <section class="page-header">
    <h1>MENTORS</h1>
    Here's a list of mentors! Click to get details!
  </section>
  <% @mentors.each do |mentor| %>
  <div class="col-md-4 mentor-panel">
    <div class="panel panel-default">
      <ul class="list-group">
        <li class="list-group-item index-image"><img src="<%= mentor.picture %>" width="100%" /></li>
        <li class="list-group-item">
          <h4 class="list-group-item-heading mentor-name"><%= mentor.name %></h4>
        </li>
        <li class="list-group-item">
          <h4 class="list-group-item-heading">Location: <%= mentor.location %></h4>
          <h4 class="list-group-item-heading">Timezone: <%= mentor.timezone %></h4>
        </li>
        <li class="list-group-item">
          <p class="list-group-item-text"><%= link_to "View details about #{mentor.name}", mentor_path(mentor) %></p>
        </li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/mentors/new.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>


<div class="container services-container">
  <div class="row">
    <div class="col-md-12 services-header">
      MENTOR
      <div>
        Create Ye a New Mentor Account
        <!-- These are the things we do. -->
      </div>
    </div>
  </div>
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <%= form_for @mentor do |f| %>
      <div class="form-group">
        <span>*</span><%= f.label :location, "Location: " %>
        <%= f.text_field :location, placeholder: "Location", class: "form-control" %>
      </div>
      <div class="form-group">
        <span>*</span><%= f.label :timezone, "Time Zone: " %>
        <%= f.select :mentor_timezone_id, options_from_collection_for_select(@timezones, "id", "name"),
          {:prompt => "Select field"}, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <span>*required</span><br />
        <%= f.submit "Create Profile", class: "btn btn-turing btn-lg btn-block", id:"complete-profile" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/mentors/show.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-3 col-md-offset-3">
      <span class="mentor-name"><%= @mentor.name %></span>
      <img src="<%= @mentor.picture %>" width="100%">
    </div>
    <div class="col-md-3">
      <div class="mentor-info">
        Email Address: <%= @mentor.email %><br />
        Slack: <%= @mentor.slack_name %><br />
        Location: <%= @mentor.location %><br />
        Timezone: <%= @mentor.timezone %><br />
        Bio: <%= @mentor.bio %><br />
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<nav class="navbar navbar-default navbar-clear">
  <%= render partial: "shared/navbar" %>
</nav>
<%= render partial: "shared/banner" %>
<%= render partial: "shared/services" %>

app/views/pages/show.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>
<%= render partial: "shared/services" %>

app/views/shared/_banner.html.erb
<div class="banner-image">
  <div class="container banner-text">
    PIRATES YE BE WARNED
    <div>mentoring opportunites abound</div>
    <% if !current_user || !(current_user.mentor || current_user.student if current_user) %>
      <div class="btn btn-turing">
        Sign up as a Mentor!
      </div>
      <div class="btn btn-turing">
        Sign up as a Student!
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar-header">
    <%= link_to root_path, class:"navbar-brand" do %>
      MENTOR<span>SHIP</span>
    <% end %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
        <li><%= link_to "How does it work?", how_path %></li>
      <% end %>
      <li><%= link_to "Browse Students", students_path %></li>
      <li><%= link_to "Browse Mentors", mentors_path %></li>
      <% if current_user %>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Sign Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Sign Up or Log In", lets_go_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->

app/views/shared/_services.html.erb
<div class="container services-container">
  <div class="row">
    <div class="col-md-12 services-header">
      SERVICES
      <div>
        These be th' thin's we do.
        <!-- These are the things we do. -->
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <i class="fa fa-github fa-2x first" aria-hidden="true"></i>
      <div class="services-description">
        Sign in wit' ye github account
      </div>
    </div>
    <div class="col-md-4">
      <i class="fa fa-paper-plane fa-2x second" aria-hidden="true"></i>
      <div class="services-description">
        Complete ye profile as a mentor or a student
      </div>
    </div>
    <div class="col-md-4">
      <i class="fa fa-rocket fa-2x third" aria-hidden="true"></i>
      <div class="services-description">
        Find a scoundrel based on location, timezone, cohort, or interest.
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>


<div class="container services-container">
  <div class="row">
    <div class="col-md-12 services-header">
      STUDENT PROFILE
      <div>
        Do the things.
        <!-- These are the things we do. -->
      </div>
    </div>
  </div>
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
        This is where the things would go!
    </div>
  </div>
</div>

app/views/students/index.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>

<div class="container">
  <section class="page-header">
    <h1>STUDENTS</h1>
    Here's are our registered students! Click to get details!
  </section>
  <% @students.each do |student| %>
  <div class="col-md-4 mentor-panel">
    <div class="panel panel-default">
      <ul class="list-group">
        <li class="list-group-item profile-image"><%= image_tag student.picture %></li>
        <li class="list-group-item">
          <h4 class="list-group-item-heading mentor-name"><%= student.name %></h4>
        </li>
        <li class="list-group-item">
          <h4 class="list-group-item-heading">
            Cohort: <%= student.cohort.id %>
          </h4>
        </li>
        <li class="list-group-item">
          <p class="list-group-item-text"><%= link_to "View details about #{student.name}", student_path(student) %></p>
        </li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/students/new.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>


<div class="container services-container">
  <div class="row">
    <div class="col-md-12 services-header">
      STUDENT PROFILE
      <div>
        Do the things.
        <!-- These are the things we do. -->
      </div>
    </div>
  </div>
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <%= form_for @student do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="form-group">
        <%= f.collection_select :cohort_id, Cohort.all, :id, :id, { prompt: "Choose your cohort" }, { class:"form-control" }  %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Student Profile", class: "btn btn-turing btn-lg btn-block", id: "complete-student" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-3 col-md-offset-3">
      <span class="mentor-name"><%= @student.name %></span>
      <img src="<%= @student.picture %>" width="100%">
    </div>
    <div class="col-md-3">
      <div class="mentor-info">
        Email Address: <%= @student.email %><br />
        Slack: <%= @student.slack_name %><br />
        Bio: <%= @student.bio %><br />
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>


<div class="container services-container">
  <div class="row">
    <div class="col-md-12 services-header">
      PROFILE
      <div>
        We need a few more thin's to complete ye profile.
        <!-- These are the things we do. -->
      </div>
    </div>
  </div>
  <div class="row">
    <div class="well col-md-4 col-md-offset-4">
      <%= form_for @user do |f| %>
      <div class="update-profile">
        <div class="form-group">
          <span>*</span><%= f.label :email, "E-Mail: " %>
          <%= f.text_field :email, placeholder: "E-Mail Address", class: "form-control" %>
        </div>
        <div class="form-group">
          <span>*</span><%= f.label :bio, "Bio: " %>
          <%= f.text_area :bio, class: "form-control", placeholder: "Taking stock: you've got a pistol with only one shot, a compass that doesn't point north ... and no ship. You are without a doubt the worst pirate I have ever heard of.", rows: 5 %>
        </div>
        <div class="form-group">
          <span>*</span><%= f.label :slack_name, "Slack Name: " %>
          <%= f.text_field :slack_name, class: "form-control", placeholder: "@something" %>
        </div>
      </div>
      <div class="form-group">
        <span>*required</span>
        <%= f.submit "Update Profile", class: "btn btn-turing btn-lg btn-block", id:"complete-profile" %>
      </div>

      <% end %>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>

<div class="container services-container">
  <div class="row">
    <div class="col-md-12 services-header">
      LET'S GO!
      <div>
        on your marks... get set!
      </div>
    </div>
  </div>
  <div class="row">
    <div class="well col-md-6 col-md-offset-3 sign-up-section">
      <span class="primary">Sign-up with your Github Account Today!</span>
      <span class="muted-text">Something less important goes here.</span>
      <hr>
      <%= link_to login_path, class:"btn btn-turing btn-lg github-signup" do %>
        <i class="fa fa-github-square fa-2x" aria-hidden="true"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-default navbar-opaque">
  <%= render partial: "shared/navbar" %>
</nav>
<div class="container services-container">
  <div class="row">
    <div class="col-md-12 services-header">
      DASHBOARD
      <div>
        These are the dashboard things
      </div>
    </div>
  </div>
  <div class="row">
    <ul class="list-group col-md-4 col-md-offset-4">
      <li class="list-group-item profile-image"><%= image_tag @user.picture %></li>
      <li class="list-group-item">Name: <b><%= @user.name %></b></li>
      <li class="list-group-item">
        E-Mail:
        <% if @user.email %>
          <b><%= @user.email %></b>
        <% else %>
          <%= link_to "complete your profile", edit_user_path(current_user), class: "profile-highlight" %>
        <% end %>
      </li>
      <li class="list-group-item">
        Bio:
        <% if @user.bio %>
          <b><%= @user.bio %></b>
        <% else %>
          <%= link_to "complete your profile", edit_user_path(current_user), class: "profile-highlight" %>
        <% end %>
      </li>
       <% if @user.student %>
       <li class="list-group-item">
         Cohort:
         <b><%= @user.student.cohort.id %></b>
       </li>
       <% end %>
      <li class="list-group-item button-section">
        <p>Do things:</p>
        <section><%= link_to "Edit Profile", edit_user_path(current_user), class:"btn btn-turing btn-section" %></section>
        <section>
        <% if @user.student && @user.student.active %>
          <%= link_to "Deactivate Student Profile", deactivate_student_path(id: current_user.id), class:"btn btn-turing btn-section" %>
        <% elsif @user.student && !@user.student.active %>
          <%= link_to "Activate Student Profile", activate_student_path(id: current_user.id), class:"btn btn-turing btn-section" %>
        <% else %>
          <%= link_to "Create Student Profile", new_student_path, class:"btn btn-turing btn-section" %>
        <% end %>
        </section>

        <section>
          <% if @user.mentor && @user.mentor.active %>
            <%= link_to "Deactivate Mentor Profile", deactivate_mentor_path(id: current_user.id), class:"btn btn-turing btn-section" %>
          <% elsif @user.mentor && !@user.mentor.active %>
            <%= link_to "Activate Mentor Profile", activate_mentor_path(id: current_user.id), class: "btn btn-turing btn-section" %>
          <% else %>
            <%= link_to "Create Mentor Profile", new_mentor_path, class: "btn btn-turing btn-section" %>
          <% end %>
        </section>
      </li>
    </ul>
  </div>
</div>